<script setup lang="ts">
import { computed, ref } from 'vue'

const props = defineProps<{
  layoutData: any
  searchQuery?: string
}>()

const pages = computed(() => {
  if (Array.isArray(props.layoutData)) return props.layoutData
  if (props.layoutData?.pages) return props.layoutData.pages
  // If it's a single page wrapped
  if (props.layoutData?.html) return [props.layoutData]
  return []
})

const containerRef = ref<HTMLDivElement | null>(null)
defineExpose({ containerRef })
</script>

<template>
  <div 
    ref="containerRef"
    class="flex flex-col flex-1 min-h-0 bg-[#4a4a4a] overflow-y-auto py-6 px-4 items-center pdf-document-container text-selection-zone"
  >
    <!-- Render the exact HTML generated by the python script -->
    <div
      v-for="(page, pIdx) in pages"
      :key="pIdx"
      v-html="page.html"
    ></div>
  </div>
</template>

<style>
/* Estilos globales para la compatibilidad con PDF.js/useTextSelection */
.pdf-span {
  user-select: text;
  -webkit-user-select: text;
}
.pdf-span::selection {
  background: rgba(0, 120, 255, 0.25);
}
</style>
