<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  layoutData: any
  searchQuery?: string
}>()

const emit = defineEmits<{
  (e: 'capture-block', payload: { text: string; id?: string }): void
}>()

// Default fallback structure in case the JSON is slightly different
const pages = computed(() => {
  if (Array.isArray(props.layoutData)) return props.layoutData
  if (props.layoutData?.pages) return props.layoutData.pages
  // If it's a single page wrapped
  if (props.layoutData?.html) return [props.layoutData]
  return []
})

// Delegated click handler since v-html elements are not reactive in Vue
function handlePageClick(e: MouseEvent) {
  const target = e.target as HTMLElement
  const span = target.closest('.pdf-span') as HTMLElement | null
  
  if (span) {
    const text = span.innerText || span.textContent || ''
    emit('capture-block', { text, id: span.id })
  }
}
</script>

<template>
  <div 
    class="flex flex-col flex-1 min-h-0 bg-[#4a4a4a] overflow-y-auto py-6 px-4 items-center"
    @click="handlePageClick"
  >
    <!-- Render the exact HTML generated by the python script -->
    <div
      v-for="(page, pIdx) in pages"
      :key="pIdx"
      v-html="page.html"
    ></div>
  </div>
</template>

<style>
/* CSS adicional en caso de que lo necesite el HTML estático */
.pdf-span {
  transition: background-color 0.2s;
  border-radius: 2px;
}
/* Highlight behavior si alguna vez lo agregan */
.pdf-span.search-highlight {
  background-color: rgba(250, 200, 0, 0.5) !important;
  outline: 1px solid rgba(200, 150, 0, 0.5);
}
</style>
